### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by zx900930** [loblab/noip-renew#36]
windows server 2016 standard
python 3.8.2
error log:
```
DevTools listening on ws://127.0.0.1:53942/devtools/browser/b4ad2ef3-b166-4c3a-b96b-07f18308600a
[2020/08/26 16:14:41] - Debug level: 2
[2020/08/26 16:14:41] - Opening https://www.noip.com/login...
[0826/161443.832:INFO:CONSOLE(61)] "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.", source: https://www.googleadservices.com/pagead/conversion.js (61)
[2020/08/26 16:14:44] - Logging in...
[2020/08/26 16:14:44] - Incorrect padding
Traceback (most recent call last):
  File "noip-renew.py", line 166, in run
    self.login()
  File "noip-renew.py", line 76, in login
    ele_pwd.send_keys(base64.b64decode(self.password).decode('utf-8'))
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "noip-renew.py", line 200, in <module>
    sys.exit(main())
  File "noip-renew.py", line 181, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "noip-renew.py", line 172, in run
    subprocess.call(['/usr/local/bin/noip-renew-skd.sh', "0", "0", "False"])
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable


Current directory:
C:\Install\noip-renew

Command to be executed:
"C:\Windows\py.exe"  "noip-renew.py" "username" "password" 2
```
exception.png
![image](https://user-images.githubusercontent.com/734749/91280830-a1d65180-e787-11ea-92bb-4f2a9d3fc5da.png)

**Comment by michaeleekk** [comment]
@zx900930 The script expects you to input a base64 encoded string from your password. Same issue with #61.

**Comment by zx900930** [comment]
@michaeleekk sorry, I forgot to close this issue.
I already changed that part into plaintext and it's working for more than 5 months now.

**Comment by sunnyd24** [comment]
@zx900930 I am hoping you can help as it seem you have it working on windows. 

How did you get this working on Windows (without debian or docker)? 
Is there any advice/steps you can give or share code that works?

I have modified noip-renew.py (v1.6.0) to comment out "subprocess.call", lines 132-135 and 201-204

I have been using Python 3.10.4 with the manual command line: "noip-renew.py _myusername_ _mypasswordinbase64_ 2" and also tried your batch script above, but neither work. See below for error log..........any ideas?

```
DevTools listening on ws://127.0.0.1:53105/devtools/browser/1abeaa5e-7c10-4461-a99f-efbdcc94f847
[2022/05/13 00:37:16] - Debug level: 2
[2022/05/13 00:37:16] - Opening https://www.noip.com/login...
[0513/003717.326:INFO:CONSOLE(26)] "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.", source: https://www.googleadservices.com/pagead/conversion.js (26)
[2022/05/13 00:37:18] - Logging in...
[0513/003721.123:INFO:CONSOLE(26)] "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.", source: https://www.googleadservices.com/pagead/conversion.js (26)
[2022/05/13 00:37:28] - my.noip.com page could not load
```

I haven't even got around to swapping the cronjob with task scheduler yet!

**Comment by zx900930** [comment]
@sunnyd24 That did work 2 years ago, but now I'm switching to docker solution simaofsilva/noip-renewer

**Comment by sunnyd24** [comment]
@zx900930 Many thanks, the solution recommended above seems to work flawlessly on a windows docker but the new github is here location is here:
[simao-silva/noip-renewer](https://github.com/simao-silva/noip-renewer)
