### ISSUE TITLE
[Docker] No hosts or host table rows not found

### ISSUE THREAD

**Issue by snakuzzo** [loblab/noip-renew#56]
Hi,
if I run noip-renew from shell everything works fine.
Running on docker I got "No hosts or host table rows not found"

I followed these steps:

```
export my_username='myusername'
export my_password='mypassword'
export my_host_num='1'
export debug_lvl=2
docker build -t loblab/selenium:debian .
```

and then (not considering error about `No such file or directory: '/usr/local/bin/noip-renew-skd.sh'` at the end of run) I've got this...

```
$  docker run --network host loblab/selenium:debian ${my_username} ${my_password} ${my_host_num} ${debug_lvl}
[2021/02/17 22:57:10] - Debug level: 1
[2021/02/17 22:57:10] - Opening https://www.noip.com/login...
[2021/02/17 22:57:12] - Logging in...
[2021/02/17 22:57:15] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/02/17 22:57:18] - No hosts or host table rows not found
Traceback (most recent call last):
  File "/home/loblab/noip-renew.py", line 167, in run
    if not self.update_hosts():
  File "/home/loblab/noip-renew.py", line 90, in update_hosts
    hosts = self.get_hosts()
  File "/home/loblab/noip-renew.py", line 159, in get_hosts
    raise Exception("No hosts or host table rows not found")
Exception: No hosts or host table rows not found
```

- `my_host_num` variable was taken as debug level
- No hosts or host table rows not found

**Comment by RomyxBaps** [comment]
Same error here. What's the solution ?

**Comment by michaeleekk** [comment]
@snakuzzo @RomyxBaps Sometimes there will be pop up boxes shown and the script will be failed. You might want to check the debug1.png, debug2.png and exception.png that the script produced. You could output the images by,

```shell
# list out all closed containers to find the container id
docker ps -a

# export the files assuming the container id is abc123
docker cp abc123:/home/loblab/debug1.png .
docker cp abc123:/home/loblab/debug2.png .
docker cp abc123:/home/loblab/exception.png .
```

You can see the problem probably in debug2.png, as that is the screenshot taken in the second step.

**Comment by snakuzzo** [comment]
I think popup is not the problem.
As I said before...it works fine outside docker.
It doesn't work inside docker...
Anyway...@michaeleekk I tried...but...

```
snakuzzo@SnakuzzoWork:~/noip_renew_dir$ docker ps -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                      PORTS                          NAMES
a1ef2668d6e9   loblab/selenium:debian   "python3 /home/lobla…"   31 seconds ago   Exited (2) 20 seconds ago                                  objective_noyce
snakuzzo@SnakuzzoWork:~/noip_renew_dir$ docker cp a1ef2668d6e9:/home/loblab/debug1.png .
Error: No such container:path: a1ef2668d6e9:/home/loblab/debug1.png
```

I tried mounting a volume...

`docker run --network host -v /home/snakuzzo/noip_renew_dir:/home/lolab loblab/selenium:debian ${noip_username} ${noip_password}`

but no files are written...

```
snakuzzo@SnakuzzoWork:~/noip_renew_dir$ pwd
/home/snakuzzo/noip_renew_dir
snakuzzo@SnakuzzoWork:~/noip_renew_dir$ docker run --network host -v /home/snakuzzo/noip_renew_dir:/home/lolab loblab/selenium:debian ${noip_username} ${noip_password}
/usr/local/bin/noip-renew-skd.sh: line 9: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 9: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 13: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 13: sudo: command not found
[2021/03/13 18:04:22] - Debug level: 1
[2021/03/13 18:04:22] - Opening https://www.noip.com/login...
[2021/03/13 18:04:25] - Logging in...
[2021/03/13 18:04:28] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/03/13 18:04:31] - No hosts or host table rows not found
snakuzzo@SnakuzzoWork:~/noip_renew_dir$ ls -lart
total 8
drwxr-xr-x 122 snakuzzo snakuzzo 4096 mar 13 19:03 ..
drwxrwxr-x   2 snakuzzo snakuzzo 4096 mar 13 19:03 .
```

**Comment by michaeleekk** [comment]
@snakuzzo can you try `docker container prune` and rerun the docker command again ? I once had the same problem as you and cleaning up the finished containers solved my problems.

And for your info, if you didn’t add `--rm` in your docker run command, the container hasn’t been cleaned up yet and could be found with `docker ps -a`. If you know the exact path of your files, you could copy the files out of that finished container with `docker cp`.

**Comment by snakuzzo** [comment]
Done, but same result...

```
snakuzzo@SnakuzzoWork:~$ docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
7e3bcda528c7fb1460ad6fc53be6af1f0873448c14775ba306787b9434c4fe83
c3e7579ad83db27856c5b18f1663777e95911444a0c48d7d5b81cf00e759d6a4
63059f6af38add0917cc3d1a1e0b84de614755af777307724b844f6558faf058

Total reclaimed space: 422.7kB
snakuzzo@SnakuzzoWork:~$ docker container ls -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
snakuzzo@SnakuzzoWork:~$ docker run --network host loblab/selenium:debian ${noip_username} ${noip_password}
/usr/local/bin/noip-renew-skd.sh: line 9: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 9: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 13: sudo: command not found
/usr/local/bin/noip-renew-skd.sh: line 13: sudo: command not found
[2021/03/13 23:12:04] - Debug level: 1
[2021/03/13 23:12:04] - Opening https://www.noip.com/login...
[2021/03/13 23:12:36] - Logging in...
[2021/03/13 23:12:36] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/03/13 23:12:40] - No hosts or host table rows not found
snakuzzo@SnakuzzoWork:~$ docker container ls -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                     PORTS     NAMES
a266a1d28b87   loblab/selenium:debian   "python3 /home/lobla…"   46 seconds ago   Exited (2) 7 seconds ago             determined_dubinsky
snakuzzo@SnakuzzoWork:~$ docker cp a266a1d28b87:/home/loblab/debug1.png .
Error: No such container:path: a266a1d28b87:/home/loblab/debug1.png
```

**Comment by michaeleekk** [comment]
@snakuzzo hmm... I’m not totally sure then...

Maybe try any of these,

1. Compare the docker files with the one you have and the one on the repo
2. pull the source again, rebuild the image and try again
3. Try to find out the differences between the one you run on the shell and the docker version to see if there are different settings 

Hope you get it works in the end.

**Comment by jellyfinuser** [comment]
Same error and impossible to find png.

**Comment by michaeleekk** [comment]
@jellyfinuser If you are using docker, you will need to either mount the folder or use `docker cp` command, I mentioned above, to copy the images out of the container.

**Comment by snakuzzo** [comment]
@michaeleekk ...

```
snakuzzo@SnakuzzoWork:~/prova$ docker run --network host loblab/selenium:debian ${noip_username} ${noip_password}
[2021/03/26 22:26:54] - Debug level: 1
[2021/03/26 22:26:54] - Opening https://www.noip.com/login...
[2021/03/26 22:26:56] - Logging in...
[2021/03/26 22:26:56] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/03/26 22:27:00] - No hosts or host table rows not found
Traceback (most recent call last):
  File "/home/loblab/noip-renew.py", line 167, in run
    if not self.update_hosts():
  File "/home/loblab/noip-renew.py", line 90, in update_hosts
    hosts = self.get_hosts()
  File "/home/loblab/noip-renew.py", line 159, in get_hosts
    raise Exception("No hosts or host table rows not found")
Exception: No hosts or host table rows not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loblab/noip-renew.py", line 200, in <module>
    sys.exit(main())
  File "/home/loblab/noip-renew.py", line 181, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "/home/loblab/noip-renew.py", line 172, in run
    subprocess.call(['/usr/local/bin/noip-renew-skd.sh', "*", "*", "False"])
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/noip-renew-skd.sh': '/usr/local/bin/noip-renew-skd.sh'
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ docker container ls -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                     PORTS     NAMES
4012beb9db2b   loblab/selenium:debian   "python3 /home/lobla…"   13 seconds ago   Exited (1) 4 seconds ago             amazing_rosalind
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ 
snakuzzo@SnakuzzoWork:~/prova$ docker cp amazing_rosalind:/home/loblab/debug1.png .
Error: No such container:path: amazing_rosalind:/home/loblab/debug1.png
```

**Comment by giorgis1987** [comment]
I have the same problem and i managed to open the debug2.png
![debug2](https://user-images.githubusercontent.com/74990746/112768924-18417780-9027-11eb-9ce9-de4dd4e56adb.png)

**Comment by snakuzzo** [comment]
Hi @giorgis1987 can you explain how to get debug images?

**Comment by giorgis1987** [comment]
in my case its:
sudo su (doesnt work without it, i get "permission denied")
sudo docker cp [container "nickname]:/home/loblab /home/[my_username]/noip-renew/

**Comment by snakuzzo** [comment]
Ok...thanks.
In previous runs I used username, but now to login it needs email address.
Fixed this and...now it worked.

Thank you and sorry for my mistake :D

**Comment by giorgis1987** [comment]
oh really? Thats strange because i can can normally login using username when running from the shell, is it different from the docker?

**Comment by snakuzzo** [comment]
I tried again...now it works with username.
