### ISSUE TITLE
Service chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by hmidani-abdelilah** [loblab/noip-renew#60]
i run script  `/usr/local/bin/noip-renew-abdelilah.sh`
the the error is
`Traceback (most recent call last):
  File "./noip-renew.py", line 200, in <module>
    sys.exit(main())
  File "./noip-renew.py", line 181, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "./noip-renew.py", line 48, in __init__
    self.browser = self.init_browser()
  File "./noip-renew.py", line 62, in init_browser
    browser = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: -4
`

i use debian 
`Distributor ID:	Debian `
`Description:	Debian GNU/Linux 10 (buster)`
`Release:	10`
`Codename:	buster
`

i use pyhon 3.7
 `/usr/local/bin/python -> /usr/bin/python3.7
`

i use  pip3 
`pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
`

i installed selenium 3 with pip3
`selenium            3.141.0   
   `

i installed chromium
`chromium-common/stable,now 88.0.4324.182-1`
`chromium-driver/stable,now 88.0.4324.182-1`
`chromium-sandbox/stable,now 88.0.4324.182-1`
`chromium/stable,now 88.0.4324.182-1`
`libchromaprint1/stable,now 1.4.3-3 `

**Comment by AWydra** [comment]
Same problem here. The problem occurred when I updated the chromium

**Comment by michaeleekk** [comment]
@hmidani-abdelilah @AWydra Did you run on devices like Raspberry PI 3 ? I got the same issue on PI3 with Docker, but worked fine on PI4 or Macbook. Maybe you would like to try running the scripts on other devices.

**Comment by hmidani-abdelilah** [comment]
> @hmidani-abdelilah @AWydra Did you run on devices like Raspberry PI 3 ? I got the same issue on PI3 with Docker, but worked fine on PI4 or Macbook. Maybe you would like to try running the scripts on other devices.

no i run it on pc not pi

**Comment by michaeleekk** [comment]
@hmidani-abdelilah I'm sorry, but I guess I don't know what the problem is then...

* Did you install the packages using `apt-get` ?
* And you might want to give the [steps using Docker](https://github.com/loblab/noip-renew#usage-with-docker) a try.

Hope that helps you solving the issue.

**Comment by hmidani-abdelilah** [comment]
@AWydra 
thank you for helping 
yes i install the packages using "apt "
i want to try docker to resolve this problem
thank you 🙏
