### ISSUE TITLE
Docker : No hosts or host table rows not found

### ISSUE THREAD

**Issue by giorgis1987** [loblab/noip-renew#65]
What am i doing wrong here guys???
This is the output:

sudo docker run --network host loblab/selenium:debian XXXXXXX ZZZZZZZZZZZZZZ(base64) 2
[2021/03/27 17:00:40] - Debug level: 2
[2021/03/27 17:00:40] - Opening https://www.noip.com/login...
[2021/03/27 17:00:44] - Logging in...
[2021/03/27 17:00:48] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/03/27 17:00:51] - No hosts or host table rows not found
Traceback (most recent call last):
  File "/home/loblab/noip-renew.py", line 167, in run
    if not self.update_hosts():
  File "/home/loblab/noip-renew.py", line 90, in update_hosts
    hosts = self.get_hosts()
  File "/home/loblab/noip-renew.py", line 159, in get_hosts
    raise Exception("No hosts or host table rows not found")
Exception: No hosts or host table rows not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loblab/noip-renew.py", line 200, in <module>
    sys.exit(main())
  File "/home/loblab/noip-renew.py", line 181, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "/home/loblab/noip-renew.py", line 172, in run
    subprocess.call(['/usr/local/bin/noip-renew-skd.sh', "*", "*", "False"])
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/noip-renew-skd.sh': '/usr/local/bin/noip-renew-skd.sh'

**Comment by hugoKs3** [comment]
Same problem from my side...
It seems the no-ip website is long to respond and the "sleep" of 1sec between login and get hosts is not enough.
I increased the sleep to 5 seconds and it worked.

**Comment by giorgis1987** [comment]
I assume that you mean the "sleep" lines (3 of them) in noip-renew.py file. I did changed them to (5) but it didnt wotk for me...
Any other ideas?

**Comment by hugoKs3** [comment]
Sorry, no other idea... it worked for me...

**Comment by sohaoo** [comment]
You should use setup.sh to install, and finally use /usr/local/bin/noip-renew-xxx.sh to execute the program

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/noip-renew-skd.sh': '/usr/local/bin/noip-renew-skd.sh'

**Comment by giorgis1987** [comment]
i had the same issue once using ubuntu server with lxqt de on top. The problem was solved when i manually created the local/bin folder that was missing. Then i run the setup.sh again and everything went smoothly while executing the binary.
Another, but more complexing thing would be to change the install directory from within the script to something else, lets say "sbin" but i dont recommend it.

**Comment by philippemiron** [comment]
I'm also getting this error, if you look at the debug png, it shows:

`reCAPTCHA failed, you will need to successfully complete reCAPTCHA before loggin in.`

**Comment by peterchs** [comment]
Haven't seen reCAPTCHA here, either at runtime of script or manually.

Although I had seen evidence of possible reCAPTCHA when I was looking at #68.

Probably game over if they've turned on reCAPTCHA :(

**Comment by philippemiron** [comment]
See my `debug2.png` following this debug messages:

```
[2021/05/14 16:28:36] - Debug level: 2
[2021/05/14 16:28:36] - Opening https://www.noip.com/login...
[2021/05/14 16:28:43] - Logging in...
[2021/05/14 16:28:52] - Opening https://my.noip.com/#!/dynamic-dns...
[2021/05/14 16:28:56] - No hosts or host table rows not found

```

For some reasons when I login manually I never get this reCAPTCHA..

![debug2](https://user-images.githubusercontent.com/387624/118330583-c751e980-b4d5-11eb-9ff2-d60ddd662c30.png)

**Comment by arooni** [comment]
same here.  evil capcha.  stupid linksys for only giving me noip :(

**Comment by peterchs** [comment]
Yup noip-renew failed now for me too, script can’t login due to reCAPCHA.  That’s that then :(

**Comment by sohaoo** [comment]
my temporary solution to the reCAPCHA problem is to use the server IP to log in to noip normally. After the reCAPCHA is verified, the verification will not be issued for a period of time. You can try it.

**Comment by philippemiron** [comment]
It didn't work for me but I don't have physical access to the machine and use it through a VPN so that might cause an issue.

> my temporary solution to the reCAPCHA problem is to use the server IP to log in to noip normally. After the reCAPCHA is verified, the verification will not be issued for a period of time. You can try it.
