### ISSUE TITLE
Message: timeout: Timed out receiving message from renderer: 10.000

### ISSUE THREAD

**Issue by Atinycookie** [loblab/noip-renew#91]
Hey guys, when I run the script I am getting the following.
It seems like chrome is timing out?

 /usr/local/bin/noip-renew/noip-renew.sh
[2021/11/09 14:26:57] - Debug level: 2
[2021/11/09 14:26:57] - Opening https://www.noip.com/login...
[2021/11/09 14:29:48] - Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: headless chrome=92.0.4515.98)

Traceback (most recent call last):
  File "/usr/local/bin/noip-renew/noip-renew.py", line 166, in run
    self.login()
  File "/usr/local/bin/noip-renew/noip-renew.py", line 70, in login
    self.browser.save_screenshot("debug1.png")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: headless chrome=92.0.4515.98)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/noip-renew/noip-renew.py", line 200, in <module>
    sys.exit(main())
  File "/usr/local/bin/noip-renew/noip-renew.py", line 181, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "/usr/local/bin/noip-renew/noip-renew.py", line 171, in run
    self.browser.save_screenshot("exception.png")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: headless chrome=92.0.4515.98)

**Comment by neothematrix** [comment]
any http proxy in the middle that you might need to configure in order to reach noip.com?

**Comment by Sailboat265** [comment]
Just my two cents reply, it's worth awhile to check your computer's DNS settings.

If you're using your router as the primary DNS, it might have some issues with caching. Pointing your computer DNS to Google (8.8.8.8) or Cloudflare (1.1.1.1). Should work well if you're experiencing page load timeout.

**Comment by neothematrix** [comment]
I encountered the same issue and fixed it in my fork: https://github.com/neothematrix/noip-renew/issues/17
I had to add "disable-gpu" to the chomedriver arguments: https://github.com/neothematrix/noip-renew/commit/59cf9bbd08f82e7fd79956176029b563cd8f7515

**Comment by ihor-sokoliuk** [comment]
had the same issue but with 10 minutes timeout.

`  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600,000
  (Session info: headless chrome=96.0.4664.110)`

fix above from @neothematrix works for me.
